In [7]:
# Importing the libraries
import numpy as np
import pandas as pd

df = pd.read_csv('dataset/shopping_customer1.csv')

# Perform data encoding and display
dfcoded = pd.get_dummies(df, prefix=['Gender', 'Marital'])
dfcoded = dfcoded.astype(int)
print(dfcoded)

   CustomerID  Age  Annual Income  Spending Score  Gender_Female  Gender_Male  \
0           1   19             15              39              0            1
1           2   21             15              81              0            1
2           3   20             16               6              1            0
3           4   23             16              77              1            0
4           5   31             17              40              1            0
5           6   22             17              76              1            0
6           7   35             18               6              1            0
7           8   23             18              94              1            0
8           9   64             19               3              0            1

   Marital_Married  Marital_Single
0                0               1
1                1               0
2                0               1
3                1               0
4                1               0
5                0               1
6                1               0
7                0               1
8                0               1

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LogisticRegression

# Importing the dataset
df = pd.read_csv('./dataset/Social_Network_Ads.csv')

df['Purchased'].value_counts()

In [10]:
df.head(10)

   CustomerID  Gender  Age  Annual Income Marital Status  Spending Score
0           1    Male   19             15         Single              39
1           2    Male   21             15        Married              81
2           3  Female   20             16         Single               6
3           4  Female   23             16        Married              77
4           5  Female   31             17        Married              40
5           6  Female   22             17         Single              76
6           7  Female   35             18        Married               6
7           8  Female   23             18         Single              94
8           9    Male   64             19         Single               3

In [11]:
#get dummies / onehot encoded
# Importing the dataset
df = pd.read_csv('./dataset/Social_Network_Ads.csv')
df = df.drop(['User ID'],axis=1)

df_getdummy = pd.get_dummies(df)
print(df_getdummy)

     Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0     19            19000          0          False         True
1     35            20000          0          False         True
2     26            43000          0           True        False
3     27            57000          0           True        False
4     19            76000          0          False         True
..   ...              ...        ...            ...          ...
395   46            41000          1           True        False
396   51            23000          1          False         True
397   50            20000          1           True        False
398   36            33000          0          False         True
399   49            36000          1           True        False

[400 rows x 5 columns]

In [12]:
df_getdummy.head(5)

   Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0   19            19000          0          False         True
1   35            20000          0          False         True
2   26            43000          0           True        False
3   27            57000          0           True        False
4   19            76000          0          False         True

In [1]:
# Drop Purchased column and convert dataframe into numpy n-darray format
from sklearn.preprocessing import StandardScaler
X = df_getdummy.drop(['Purchased'],axis=1).to_numpy()

##scale X
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Set the Purchased as target label Y

Y = df_getdummy['Purchased'].to_numpy()

NameError: name 'df_getdummy' is not defined

In [14]:
# Fitting Logistic Regression to the Training set
classifier = LogisticRegression(solver='liblinear', random_state = 0)
classifier.fit(X, Y)

NameError: name 'LogisticRegression' is not defined

In [ ]:
import sklearn.metrics as metrics
y_pred=classifier.predict(X)

accuracy = metrics.accuracy_score(Y, y_pred)
print("train accuracy: %.2f." %accuracy)

precision = metrics.precision_score(Y, y_pred)
print("train precision: %.2f." %precision)

recall = metrics.recall_score(Y, y_pred)
print("train recall: %.2f." %recall)

print(y_pred[:100])

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

#Counts of true negatives, false positives, false negatives and true positives
tn, fp, fn, tp = confusion_matrix(Y, y_pred).ravel()
print(tn, fp, fn, tp)

#Plot the confusion matrix
cm = confusion_matrix(Y, y_pred)

# Plot the confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classifier.classes_)
disp.plot(cmap=plt.cm.Blues)  # You can set normalize to 'true' or 'all' if needed
plt.title('Confusion matrix for our classifier')
plt.show()

In [ ]:
# Print classification report
print(classification_report(Y, y_pred))

In [ ]:
## Uncomment the following line and fill in your answer
## Standardise the data
## Predict using the trained model

X1 = np.array([[35, 140000, 1, 0],
               [45, 25000, 0, 1],
               [35, 6500, 1, 0]])

# Scale X1 data

X1 = scaler.fit_transform(X1) 


# Predict based on X1 data and save in y_pred

y_pred = classifier.predict(X1)
print(y_pred)